### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by ewerlopes** [miccol/Behavior-Tree#1]
Hi;

I have been taking a look in this project code these days... The organization of the code is great, by the way. However, I realized there are some header files missing. For instance, there is no "Action/ActionNodeTemplate.h". So, I would like to know if there is any plan of yours for continuing improving the project any time soon.

Regards.

**Comment by miccol** [comment]
Hi ewerlopes, 

Thanks for interesting in the project.

ActionNodeTemplate.cpp was just an example on how an action node should look like. It is not added in the cmakelist then not compiled.
If you think this will improve the readability of the project I will add "Action/ActionNodeTemplate.h". The reason why I did not is because the cmake includes all the header files in the "include" folder. I prefer to avoid including unused headers.

You mentioned some other header file missing. Could you tell me which ones? 
I have extensively tested the ROS version of the library but not the pure C ++ one. 

Thank you
Michele

**Comment by ewerlopes** [comment]
Hi again!

Ahh.. Okay. It does make sense now not having the "Action/ActionNodeTemplate.h" since it is supposed to be just an example. The confusion started when I saw the manual (.pdf)... and then the "not resolved" warning for the header in my IDE.

Well, it would be better to have a full working environment.. Even if there are example codes. Indeed, I found your project just yesterday.. and I plan to see much of it from now on. 

I am also interested in the ROS version.. and already forked the project. I hope to be able to contribute, somehow.

Thanks for the answer.
Best Regards.
