### ISSUE TITLE
ControlNodes and BT::RUNNING

### ISSUE THREAD

**Issue by facontidavide** [miccol/Behavior-Tree#22]
This is a heads up about something that I want to discuss in more detail in a future PR.

I am looking at the code of the main ControlNodes and I am trying to understand what happens when a child returns RUNNING.

Apparently, when a child returns RUNNING, these Nodes halt the following children. 

- [Fallback](https://github.com/miccol/Behavior-Tree/blob/devel/src/fallback_node.cpp#L44)
- [Sequence](https://github.com/miccol/Behavior-Tree/blob/devel/src/sequence_node.cpp#L44)

On the other hand, **FallbackNodeWithMemory** and **SequenceNodeWithMemory** never invoke haltChildren, in any case.

Is that intentional?

In my opinion:

- Fallback with or without memory should call haltChildren(i+1) only when child return SUCCESS.
- Sequence with or without memory should call haltChildren(i+1) only when child return FAILURE.

**Comment by facontidavide** [comment]
Furthermore. The **ActionTestNode** implemented in the unit test doesn never return BT::RUNNING; therefore we are not really testing Actions which return RUNNING.

I propose to improve the unit test to explore the expected behavior.

**Comment by miccol** [comment]
Hi, yes that is intentional.
About Regular nodes

Think about this BT


![](https://user-images.githubusercontent.com/8132627/35183015-47748afc-fddf-11e7-9955-e0855e607537.png)

Imagine the situation where the object is picked and the robot is assembling the object. So the condition 'Object Picked' returns Success, the leftmost fallback returns Success, the condition ''Object Assembled' return failure and the ticks reach the action 'Assemble Object' (which returns Running).
Now, while the action  'Assemble Object' is performed the object slips out from the robot's gripper making the condition  'Object Picked'  return Failure and the action to be executed 'Pick Object' (which return running). Now the leftmost Fallback returns Running and the sequence needs to halt the next children.

About node with memory
Since they are node with memory, if a child is being executed it means that this is the first time that it is executed and the next children are still in IDLE.

**Comment by facontidavide** [comment]
ok!
